# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.5.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.5.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/shanbo/chengshanbo/git/normalization

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/shanbo/chengshanbo/git/normalization

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.5.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shanbo/chengshanbo/git/normalization/CMakeFiles /Users/shanbo/chengshanbo/git/normalization/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shanbo/chengshanbo/git/normalization/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named normal

# Build rule for target.
normal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 normal
.PHONY : normal

# fast build rule for target.
normal/fast:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/build
.PHONY : normal/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parameter.o: src/parameter.cpp.o

.PHONY : src/parameter.o

# target to build an object file
src/parameter.cpp.o:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/parameter.cpp.o
.PHONY : src/parameter.cpp.o

src/parameter.i: src/parameter.cpp.i

.PHONY : src/parameter.i

# target to preprocess a source file
src/parameter.cpp.i:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/parameter.cpp.i
.PHONY : src/parameter.cpp.i

src/parameter.s: src/parameter.cpp.s

.PHONY : src/parameter.s

# target to generate assembly for a file
src/parameter.cpp.s:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/parameter.cpp.s
.PHONY : src/parameter.cpp.s

src/recognizer.o: src/recognizer.cpp.o

.PHONY : src/recognizer.o

# target to build an object file
src/recognizer.cpp.o:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/recognizer.cpp.o
.PHONY : src/recognizer.cpp.o

src/recognizer.i: src/recognizer.cpp.i

.PHONY : src/recognizer.i

# target to preprocess a source file
src/recognizer.cpp.i:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/recognizer.cpp.i
.PHONY : src/recognizer.cpp.i

src/recognizer.s: src/recognizer.cpp.s

.PHONY : src/recognizer.s

# target to generate assembly for a file
src/recognizer.cpp.s:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/recognizer.cpp.s
.PHONY : src/recognizer.cpp.s

src/regularRule.o: src/regularRule.cpp.o

.PHONY : src/regularRule.o

# target to build an object file
src/regularRule.cpp.o:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/regularRule.cpp.o
.PHONY : src/regularRule.cpp.o

src/regularRule.i: src/regularRule.cpp.i

.PHONY : src/regularRule.i

# target to preprocess a source file
src/regularRule.cpp.i:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/regularRule.cpp.i
.PHONY : src/regularRule.cpp.i

src/regularRule.s: src/regularRule.cpp.s

.PHONY : src/regularRule.s

# target to generate assembly for a file
src/regularRule.cpp.s:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/regularRule.cpp.s
.PHONY : src/regularRule.cpp.s

src/util.o: src/util.cpp.o

.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... normal"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parameter.o"
	@echo "... src/parameter.i"
	@echo "... src/parameter.s"
	@echo "... src/recognizer.o"
	@echo "... src/recognizer.i"
	@echo "... src/recognizer.s"
	@echo "... src/regularRule.o"
	@echo "... src/regularRule.i"
	@echo "... src/regularRule.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

